### ISSUE TITLE
export pcap with wrong timestamps

### ISSUE THREAD

**Issue by descartin** [sipcapture/homer#335]
Dear all

we are seeing an issue when exporting a call flow to a pcap or text file. Seems the timestamp of the SIP packets is the moment of the exporting, almost the same for all, despite the timestamp for each packet is ok in the call flow screen. But somehow it gets modified when exporting.

could you please check why can we tune that to be the original timestamp of the packet in the DB?

thanks a lot and regards
david

**Comment by lmangani** [comment]
Hi @descartin please specify your setup is as much detail as possible. There are many different combinations nowadays.

**Comment by descartin** [comment]
hello Lorenzo

we have a captagent client in a server sending with hep3 the packets to a server which runs heplify-server and the homer-app js for the web.
Do you want me to share any particular setup file?

best regards
david

**Comment by descartin** [comment]
Dear Alexandr

do you have any update about this issue?

best regards
david

**Comment by descartin** [comment]
Dear Alexandr

do you have any update about this issue?

best regards
david

**Comment by adubovikov** [comment]
I will check it tonight

**Comment by adubovikov** [comment]
Hi,

i will check it tonight

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/456033a01d6b82dec206d6bf96d9fdf7b04041f5
but I am not sure it will fix your issue, because timestamp in the pcap file was ok. Anyway, please take it and re-check! Thank you

**Comment by descartin** [comment]
Dear Alex

we downloaded the last version of homer-app but seems the issue is still there

the flow and timestamps seem ok, but when doing export, the time seen is the moment in where you do the eexport, for all the packets of the trace.

could you please take a look?

best regards
david

**Comment by adubovikov** [comment]
David, 
sorry, i don't understand the problem, because the timestamps in the pcap are from DB, can you please send me your pcap and screenshots of callflows just to compare. Send the txt export as well.

thank you

**Comment by deniscamp1234** [comment]
No worries.

I found the problem on our side.

The SIP trunk is working now.

 

You can close this ticket.

Thanks for your assistance.

 

Denis Camp

9515007090

**Comment by descartin** [comment]
hello Alex

don't understand why the issue was closed.
Here you have the capture

![image](https://user-images.githubusercontent.com/7767994/56202461-61b77880-6043-11e9-8b61-b9529477676d.png)
and the text exported attached

best regards
david
[HEPIC-undefined-undefined-4_16_2019 12_30_31.txt](https://github.com/sipcapture/homer/files/3084429/HEPIC-undefined-undefined-4_16_2019.12_30_31.txt)

**Comment by adubovikov** [comment]
ok, @deniscamp1234 has reply "it was fixed" and I didn't know that he is not from your team

**Comment by adubovikov** [comment]
can you be sure that time on your nodejs app are accurate ?

**Comment by descartin** [comment]
Dear Alexandr

Sorry it has been a while i had some some issues.
PLease let me know how can i feed you back about this problem to get this solved. What do i need to check and pas to you

thanks a lot and regards
david

**Comment by descartin** [comment]
Dear Alexandr
PLease let me know how can i feed you back about this problem to get this solved. What do i need to check and pass to you

thanks a lot and regards
david

**Comment by jgallartm** [comment]
Hello, 

I am in the same team as the OP.  We've tested with the latest version of homer-app, and in both the pcap or text files all the packets still show the same -wrong- timestamp.
We have tried to debug the issue further, and we found this:

-When filtering by callid, the message list is correctly displayed, every message has its proper and unique Date field.
![h1](https://user-images.githubusercontent.com/3063948/60450774-e2d9e100-9c2a-11e9-8325-ade3d787f105.PNG)

-However, when we try to export that same call, the API returns wrong dates. This a summary of all the messages returned by the api/v3/export/call/messages/text API:

proto:UDP **2019-07-01T16:02:02.714Z**  
INVITE sip:528....

proto:UDP **2019-07-01T16:02:02.714Z**  
SIP/2.0 100 trying -
(...)

proto:UDP **2019-07-01T16:02:02.714Z**  
INVITE sip:52818262025
(...)

proto:UDP **2019-07-01T16:02:02.714**Z  
SIP/2.0 100 Trying
(...)

proto:UDP **2019-07-01T16:02:02.714Z**  
(...)

As you can see, all the date fields contain the same value. I hope the issue is more clear now, let me know if you need more information.

Regards

Javier

**Comment by adubovikov** [comment]
we are working on the fix

**Comment by jgallartm** [comment]
Hi,

is there any update about this issue?

Thanks

**Comment by aqsyonas** [comment]
@jgallartm We are working on your request and will update this ticket once done. Thanks for your patience.

**Comment by descartin** [comment]
Hi,

is there any update about this issue?

Thanks

**Comment by lmangani** [comment]
Thanks @giavac! Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
