### ISSUE TITLE
Export flow as PNG (version 1.3.3)

### ISSUE THREAD

**Issue by dmigardos** [sipcapture/homer#427]
Hi,

This morning we upgraded to version 1.3.3 and the upgrade appears to have broken the "Export flow as PNG" output.  The .png is created but the .png is blank with no call flow when opened.

export pcap and export text still work fine.

**Comment by adubovikov** [comment]
thank you. We will check it ASAP

**Comment by adubovikov** [comment]
@dmigardos the issue is now - the all tabs are now in high perfomance mode and use virtual scrolling. We will try to fix it, but it will be not easy

**Comment by adubovikov** [comment]
Release 1.3.6

the issue has been fixed there.

**Comment by dmigardos** [comment]
Hi Alexandr,

I've upgraded to 1.3.6
apt-cache policy homer-app
homer-app:
  Installed: 1.3.6
  Candidate: 1.3.6
  Version table:
 *** 1.3.6 500

Restarted the service
systemctl stop homer-app
systemctl start homer-app

The PNG still shows blank:
https://drive.google.com/file/d/19T-Grti6S2YOF1_dTDs9thQCrVzz38Rw/view?usp=sharing

**Comment by adubovikov** [comment]
what is UI version ?

**Comment by dmigardos** [comment]
Homer 7.9.4

**Comment by adubovikov** [comment]
then you didn't upgrade it - you still have the old version.
https://github.com/sipcapture/homer-ui/blob/master/src/VERSION.ts

**Comment by dmigardos** [comment]
Hi Alexandr,

Is the 7.9.4  build not part of the homer_installer.sh file?

Here is what we typically do:
cd /root
mkdir homer-app
cd homer-app
wget
https://github.com/sipcapture/homer-installer/raw/master/homer_installer.sh
chmod +x homer_installer.sh
./homer_installer.sh

**Comment by adubovikov** [comment]
@dmigardos looks like you have upgraded only homer-app but you have to upgrade homer-ui, therefore I recomend you use our packages - this is the best and easy way for you.

**Comment by dmigardos** [comment]
Hi, Any instructions to have your package installed under debian 9?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-install

**Comment by dmigardos** [comment]
Thank you, 7.9.7 has resolved the issue.

**Comment by adubovikov** [comment]
Perfect
