### ISSUE TITLE
Homer webapp shared pannel/dashboard issue

### ISSUE THREAD

**Issue by devBash99** [sipcapture/homer#443]
I have an issue with the homer web app. I have created some dashboard that I will like to share will all the users I have created. I selected the shared option on the dashboard setting but it seems to have no effect. I am using homer docker version. I also pulled the latest webapp image today but the issue still persists.

OS: debian 10
Homer version: 7.9.10 (docker) 

If you require any other details then kindly tell and I will provide.
Thank you!

**Comment by adubovikov** [comment]
The issue has been fixed. Please install the latest release ;-)

**Comment by devBash99** [comment]
Tested and it works. Thanks.

**Comment by devBash99** [comment]
@adubovikov  When a pannel shared it's entry is repeated in the dashboard selection dropdown for every new user. Now i believe the dashboard is copied to every new user. But is there a way for the names to not be repeated? I have attached a photo for reference .  If this should be opened as separate issue than please let me know .Thank you
![image](https://user-images.githubusercontent.com/58656223/109542994-9b82b280-7ae7-11eb-8875-679b0ffd4f54.png)

**Comment by bmgante** [comment]
Also have this problem.

**Comment by adubovikov** [comment]
sorry, please update to the latest package
it has been fixed alredy!

**Comment by bmgante** [comment]
i have homer 7.9.11 installed today, is there a new version available?

**Comment by devBash99** [comment]
@bmgante did you take a fresh pull from the master branch of homer-ui? I'm going to test it now.

**Comment by devBash99** [comment]
> @adubovikov When a pannel shared it's entry is repeated in the dashboard selection dropdown for every new user. Now i believe the dashboard is copied to every new user. But is there a way for the names to not be repeated? I have attached a photo for reference . If this should be opened as separate issue than please let me know .Thank you
> ![image](https://user-images.githubusercontent.com/58656223/109542994-9b82b280-7ae7-11eb-8875-679b0ffd4f54.png)

@adubovikov  This issue still persists. I have tested the latest release of homer app and homer ui.   The entry for shared pannel repeats for every new user that is added.

**Comment by adubovikov** [comment]
unfortunately you have to delete these dashboards in Settings->Advanced->dashboards
The DB has been copied all shared dashboards as an own local copy. Sorry about this bug.
Whats version do you use ?

**Comment by devBash99** [comment]
These are the versions I have tested today. I build them from the master branch today.

hepserver 1.54+842d096(commit number)
homer-app 1.3.22
homer-ui 7.9.12

**Comment by adubovikov** [comment]
just delete these dashboards

**Comment by devBash99** [comment]
so the way would be that be to create shared pannels then create all the users and just delete the extra pannels

**Comment by adubovikov** [comment]
Or just disable shared dashboards and after delete the wrong one and enable
again

**Comment by adubovikov** [comment]
Done. Please install homer-app-1.4.0
